version: "3.9"
services:
  backend:
    depends_on:
      - db
    image: golang:1.20rc2-bullseye
    #build:
    #  context: ./
    #  network: host
    working_dir: /usr/src/app
    volumes:
      - ${PWD}:/usr/src/app
    network_mode: "host"
    command: ["go", "run", "main.go"]
#RUN go build -v -o /usr/local/bin/app ./...

  db:
    image: postgres:15.1-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    network_mode: "host"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]


